FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libx11-dev libimlib2-dev build-essential

COPY . /repo
WORKDIR /repo
RUN make -j8 
RUN make install DESTDIR=/install

FROM ubuntu:20.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libimlib2-dev

COPY --from=builder /install /install
